/**
 * Tao Shu REST API
 * \"Spring Boot REST API for Tao Shu\"
 *
 * OpenAPI spec version: 1.0.0
 * Contact: carlosschuenck@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Turma } from './turma';


export interface Aluno {
    dataNascimento?: string;
    id?: number;
    nomeCompleto?: string;
    nomeMae?: string;
    nomePai?: string;
    turma?: Turma;
}
